### PR TITLE
[WIP] fix(angular): Fix babel-polyfill multiple instances issue

### LINKED ISSUE #77: "only one instance of babel-polyfill is allowed" Error
image

### PR DESCRIPTION
**Pull request by theiliad**
Closes #77

### CODE REVIEW

File: packages/core/src/polyfills.ts [hunk 1]
```diff
@@ -11,3 +11,14 @@
...
+// Avoid multiple instances of babel-polyfill
+function idempotentBabelPolyfill() {
+	if (!global["_babelPolyfill"] && (typeof window === "undefined" || !window["_babelPolyfill"])) {
+		return require("babel-polyfill");
+	}
+
+	return null;
+};
+
+idempotentBabelPolyfill();
```
Comment (zvonimirfras) [inline packages/core/src/polyfills.ts]: Missing newline at the end of file.
```suggestion
idempotentBabelPolyfill();

```
