### PR TITLE
Tooltips Bug Fix #89

### LINKED ISSUE #89: Tooltips for Stacked Bar & Line show onClick
Tooltips **should always be showing on hover no click**

### PR DESCRIPTION
**Pull request by darsi-an**
Fix bug #89 

Files updated: 
- core/configuration.ts: updated line chart tooltip fix. 
- core/stacked-bar-chart.ts: updated addDataPointEventListener
- core/line-chart.ts: updated addDataPointEventListener

### Updates

- list
- out
- updates
- here (and don't forget to link the issues)

### Review checklist (for reviewers only)

- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/src/line-chart.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // D3 Imports
-import { select } from "d3-selection";
+import { select, selectAll, mouse } from "d3-selection";
```
Comment (theiliad) [inline packages/core/src/line-chart.ts]: Is `selectAll` used in this file?

File: packages/core/src/line-chart.ts [hunk 2]
```diff
@@ -206,24 +206,56 @@ export class LineChart extends BaseAxisChart {
...
 	}
 
+
 	addDataPointEventListener() {
 		const self = this;
-		const { thresholds } = this.options;
+		const { accessibility } = this.options;
 
-		this.svg.selectAll("circle.dot")
+		this.svg.selectAll("gLines")
```
Comment (theiliad) [inline packages/core/src/line-chart.ts]: Don't think the selector `gLines` will match any elements...?

File: packages/core/src/line-chart.ts [hunk 3]
```diff
@@ -206,24 +206,56 @@ export class LineChart extends BaseAxisChart {
...
-					.attr("stroke", self.colorScale[d.datasetLabel](d.label))
+					.attr("stroke-width", accessibility ? strokeWidthAccessible : strokeWidth)
+					.attr("stroke", accessibility ? self.colorScale[d.datasetLabel](d.label) : "none")
 					.attr("stroke-opacity", Configuration.lines.points.mouseout.strokeOpacity);
-			})
-			.on("click", function(d) {
+
+				self.hideTooltip();
+			});
+
```
Comment (theiliad) [inline packages/core/src/line-chart.ts]: What is the purpose of the entire piece of code above? Seems like the code below is enough for line chart

File: packages/core/src/stacked-bar-chart.ts [hunk 4]
```diff
@@ -1,5 +1,5 @@
 // D3 Imports
-import { select } from "d3-selection";
+import { select, selectAll, mouse } from "d3-selection";
```
Comment (theiliad) [inline packages/core/src/stacked-bar-chart.ts]: `selectAll` isn't used in this file either
